version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./dev.db
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your_nextauth_secret_here
    volumes:
      - ./dev.db:/app/dev.db
    restart: unless-stopped

  # Opcional: Base de datos PostgreSQL para producción
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: copiloto_emprendedor
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

# volumes:
#   postgres_data:
